services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    # container_name: dreams_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POP_URL: ${POP_URL:-POP_URL}
      TARGET_SRID: ${TARGET_SRID:-3857}
      ADMIN_BUFFER: ${ADMIN_BUFFER:-15000}
      DEFAULT_POINT_IF_SMALL_AREA: ${DEFAULT_POINT_IF_SMALL_AREA:-1000}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql 
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    command:
    #  "postgres"
    # - "-c" "work_mem=50MB"
    # - "-c" "checkpoint_completion_target=0.9"
    # - "-c" "max_wal_senders=0"
    # - "-c" "random_page_cost=1.0"
    # - "-c" "wal_level=minimal"
      - -c
      - shared_buffers=2GB
      - -c
      - maintenance_work_mem=4GB
      - -c
      - checkpoint_timeout=30min
      - -c
      - max_wal_size=8GB
    
  importer:
    # If this image name changes, swap to a known-good osm2pgsql image.
    image: iboates/osm2pgsql:2.1.1
    # container_name: dreams_importer
    profiles: ["import"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      PBF_URL: ${PBF_URL}
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      TARGET_SRID: ${TARGET_SRID:-3857}
    volumes:
      - ./importer:/importer
      - ./sql:/sql
    entrypoint: ["/bin/sh", "/importer/import.sh"]

volumes:
  pgdata:
  cache:

